# Generated by Django 5.2 on 2025-05-06 14:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threads', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='название')),
                ('description', models.TextField(verbose_name='описание')),
                ('format', models.CharField(choices=[('bootcamp', 'Bootcamp'), ('workshop', 'Workshop'), ('offline', 'Offline'), ('online', 'Online')], max_length=20, verbose_name='формат курса')),
                ('prefix', models.CharField(max_length=10, verbose_name='префикс')),
                ('schedule', models.JSONField(blank=True, null=True, verbose_name='расписание')),
            ],
            options={
                'verbose_name': 'курс',
                'verbose_name_plural': 'курсы',
            },
        ),
        migrations.AlterModelOptions(
            name='department',
            options={'verbose_name': 'подразделение', 'verbose_name_plural': 'подразделения'},
        ),
        migrations.CreateModel(
            name='EducationThread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.CharField(max_length=50, unique=True, verbose_name='артикул')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='дата начала')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='дата окончания')),
                ('is_open_start', models.BooleanField(default=False, verbose_name='с открытой датой начала')),
                ('is_open_end', models.BooleanField(default=False, verbose_name='с открытой датой окончания')),
                ('is_auto_generated', models.BooleanField(default=False, verbose_name='автогенерация')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='threads', to='threads.course', verbose_name='курс')),
            ],
            options={
                'verbose_name': 'образовательные потоки',
            },
        ),
    ]
