# Generated by Django 5.2 on 2025-05-06 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('threads', '0002_course_alter_department_options_educationthread'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='educationthread',
            options={'verbose_name': 'образовательный поток', 'verbose_name_plural': 'потоки'},
        ),
    ]
