# Generated by Django 5.2 on 2025-05-06 14:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('threads', '0003_alter_educationthread_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_id', models.CharField(max_length=50, unique=True)),
                ('contract_type', models.CharField(choices=[('hourly_presenter', 'Hourly Presenter'), ('author', 'Author'), ('project', 'Project'), ('corporate_training', 'Corporate Training')], max_length=30)),
                ('currency', models.CharField(default='RUB', max_length=3)),
                ('comment', models.TextField(blank=True, null=True)),
                ('is_template', models.BooleanField(default=False)),
                ('allow_new_accruals', models.BooleanField(default=True)),
                ('non_financial_terms', models.JSONField(blank=True, null=True)),
                ('signed_at', models.DateField(blank=True, null=True)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('validity_date', models.DateField(blank=True, null=True)),
                ('actual_created_at', models.DateField(auto_now_add=True)),
                ('replaced_contract', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replacements', to='contracts.contract')),
            ],
            options={
                'verbose_name': 'контракт',
                'verbose_name_plural': 'контракты',
            },
        ),
        migrations.CreateModel(
            name='Contractor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='имя')),
                ('contractor_type', models.CharField(choices=[('individual', 'Individual'), ('ip', 'IP'), ('self_employed', 'Self-Employed'), ('legal_entity', 'Legal Entity'), ('non_resident', 'Non-Resident')], max_length=20, verbose_name='тип контрагента')),
                ('inn', models.CharField(blank=True, max_length=12, null=True, unique=True)),
                ('kpp', models.CharField(blank=True, max_length=9, null=True)),
                ('passport_data', models.JSONField(blank=True, null=True)),
                ('bank_details', models.JSONField(blank=True, null=True)),
                ('elba_id', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'контрагент',
                'verbose_name_plural': 'контрагенты',
            },
        ),
        migrations.CreateModel(
            name='ContractManagerAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='managers', to='contracts.contract')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='contract',
            name='contractor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='contracts.contractor'),
        ),
        migrations.CreateModel(
            name='PresenterHourlyContract',
            fields=[
                ('contract', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='presenter_contract', serialize=False, to='contracts.contract')),
                ('hourly_rate', models.DecimalField(decimal_places=4, max_digits=10)),
                ('payment_schedule', models.CharField(choices=[('weekly', 'Weekly'), ('monthly', 'Monthly'), ('after_flow', 'After Flow')], max_length=20)),
                ('payment_day_of_week', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('role', models.CharField(choices=[('lead', 'Lead'), ('co_presenter', 'Co-Presenter')], max_length=20)),
                ('tax_compensation', models.BooleanField(default=False)),
                ('compensation_details', models.JSONField(blank=True, null=True)),
                ('hours_worked', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('rate_type', models.CharField(default='standard', max_length=10)),
                ('contractor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contracts.contractor')),
            ],
            options={
                'verbose_name': 'контракт с ведущим (почасовой)',
                'verbose_name_plural': 'контракты с ведущими (почасовые)',
            },
        ),
        migrations.CreateModel(
            name='AuthorContract',
            fields=[
                ('contract', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='author_contract', serialize=False, to='contracts.contract')),
                ('commission_type', models.CharField(choices=[('fixed', 'Fixed'), ('percentage_revenue', 'Percentage Revenue'), ('percentage_profit', 'Percentage Profit'), ('hourly_rate', 'Hourly Rate'), ('experimental', 'Experimental'), ('fixed_plus_percentage', 'Fixed + Percentage')], max_length=30)),
                ('commission_value', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fixed_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('percentage_value', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('hourly_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_global', models.BooleanField(default=True)),
                ('dynamic_commission_formula', models.JSONField(blank=True, null=True)),
                ('experimental_details', models.JSONField(blank=True, null=True)),
                ('first_flow_bonus', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='threads.course')),
                ('linked_hourly_contract', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='contracts.presenterhourlycontract')),
            ],
            options={
                'verbose_name': 'контракт с автором',
                'verbose_name_plural': 'контракты с авторами',
            },
        ),
    ]
